import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "HomeHaven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={`${roboto.variable} font-roboto`}>
        <div>
          <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
